export const State = {
  invalid: 0,
  start: 1,
  ident: 2,
  builtin: 3,
  str_lit: 4,
  str_lit_backslash: 5,
  percent: 6,
  mult_line_str_lit: 7,
  mult_line_strlit_line: 8,
  char_lit: 9,
  char_lit_backslash: 10,
  back_slash: 11,
  slash: 12,
  rangle: 13,
  langle: 14,
  equal: 15,
  plus: 16,
  minus: 17,
  bang: 18,
  pipe: 19,
  ampersand: 20,
  asterisk: 21,
  saw_at_sign: 22,
  zero: 23,
  int_lit_dec: 24,
  int_lit_dec_nounder: 25,
  int_lit_bin_nounder: 26,
  int_lit_oct_nounder: 27,
  int_lit_hex_nounder: 28,
  int_lit_bin: 29,
  int_lit_oct: 30,
  int_lit_hex: 31,
  num_dot_dec: 32,
  float_lit: 33,
  float_lit_nounder: 34,
  float_exponent_usize: 35,
  float_exponent_num_nounder: 36,
  float_exponent_num: 37,
  line_comment: 38,
} as const;

export type state = (typeof State)[keyof typeof State];
